typography_spectrum: 0.3131548597011715
color:
  saturation: 0.6348671927116811
  brandStrength: 0.05119033227674663
  lightness: 0.825107031268999
  brandColors:
    - '#EFEFEF'
    - '#111111'
    - '#CACACA'
    - '#979797'
    - '#616161'
  rhythmicContrast: 0.7019105805084109
layout_spectrum: 0.9027927
author:
  email: lars.millberg@gmail.com
  url: larsmillberg.com
name: Lars Millberg Photography
navigation:
  - name: Pictures for sale here
    url: 'http://500px.com/larsmillberg'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The world as I see it
description: Pictures for sale here
